### ISSUE TITLE
Configurable max message size?

### ISSUE THREAD

**Issue by IntrepidCharm** [stylefruits/gniazdo#22]
I'm getting a Jetty exception:

```
2017-07-30 11:31:05.514:WARN:oejwc.Parser:WebSocketClient@1487230025-10: 
org.eclipse.jetty.websocket.api.MessageTooLargeException: Text message size [67527] exceeds maximum size [65536]
	at org.eclipse.jetty.websocket.api.WebSocketPolicy.assertValidTextMessageSize(WebSocketPolicy.java:140)
	at org.eclipse.jetty.websocket.common.Parser.assertSanePayloadLength(Parser.java:127)
	at org.eclipse.jetty.websocket.common.Parser.parseFrame(Parser.java:480)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:252)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:675)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:505)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:186)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```

Wondering if there's a way I can currently configure this max message size using gniazdo?

**Comment by xsc** [comment]
@IntrepidCharm I'm not sure if this addresses your problem but you could try creating the `WebSocketClient` yourself:

```clojure
(require '[gniazdo.core :as ws])
(let [message-size (* 1024 1024)
      client (doto (ws/client)
               (.setMaxBinaryMessageBufferSize message-size)
               (.setMaxTextMessageBufferSize message-size))]
  (ws/connect "ws://..." {:client client, ...}))
```

**Comment by IntrepidCharm** [comment]
Thanks for the reply @xsc.

I actually already tried this with no success, should have mentioned that in my opening post.

**Comment by IntrepidCharm** [comment]
Managed to fix it, just had to set a variable on the policy:

```clojure
(let [client (new WebSocketClient (new SslContextFactory))]
             (.setMaxTextMessageSize (.getPolicy client) max-text-message-size)
             (.start client)
             (ws/connect
              @the-gateway
              :client client
              ...
```
